import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header/header.jsx";
import Footer from "./footer/footer.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HousePlants",
  description: "Generated by Eloise Cresswell",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
